.TH "Config" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBfail\fP (const std::string &msg)"
.br
.ti -1c
.RI "void \fBsetLastTime\fP (int64_t newTime)"
.br
.ti -1c
.RI "void \fBshown_demo_msg\fP ()"
.br
.ti -1c
.RI "void \fBload\fP (const boost::filesystem::path &where)"
.br
.ti -1c
.RI "void \fBwrite\fP ()"
.br
.ti -1c
.RI "bool \fBread\fP (const std::string &filename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfilename\fP"
.br
.ti -1c
.RI "bool \fBupdateList\fP"
.br
.ti -1c
.RI "bool \fBupdateTigs\fP"
.br
.ti -1c
.RI "bool \fBupdateCache\fP"
.br
.ti -1c
.RI "bool \fBfirst_time\fP"
.br
.ti -1c
.RI "bool \fBdebug\fP"
.br
.ti -1c
.RI "bool \fBseen_demo_msg\fP"
.br
.ti -1c
.RI "int64_t \fBlastTime\fP"
.br
.ti -1c
.RI "std::string \fBbaseUrl\fP"
.br
.ti -1c
.RI "std::string \fBimageUrl\fP"
.br
.ti -1c
.RI "std::string \fBlocalPath\fP"
.br
.ti -1c
.RI "std::string \fBimagePath\fP"
.br
.ti -1c
.RI "std::string \fBdefDevname\fP"
.br
.ti -1c
.RI "std::string \fBdefPaypal\fP"
.br
.ti -1c
.RI "std::string \fBuser\fP"
.br
.ti -1c
.RI "std::string \fBapi_key\fP"
.br
.ti -1c
.RI "std::string \fBpostHook\fP"
.br
.ti -1c
.RI "bool \fBautoPost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file config\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
