.TH "DataList::TigInfo" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataList::TigInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBurl\fP"
.br
.ti -1c
.RI "std::string \fBlaunch\fP"
.br
.ti -1c
.RI "std::string \fBsubdir\fP"
.br
.ti -1c
.RI "std::string \fBversion\fP"
.br
.ti -1c
.RI "std::string \fBtitle\fP"
.br
.ti -1c
.RI "std::string \fBdesc\fP"
.br
.ti -1c
.RI "std::string \fBshot\fP"
.br
.ti -1c
.RI "std::string \fBshot80x50\fP"
.br
.ti -1c
.RI "std::string \fBshot300x260\fP"
.br
.ti -1c
.RI "std::string \fBlocation\fP"
.br
.ti -1c
.RI "std::string \fBdevname\fP"
.br
.ti -1c
.RI "std::string \fBhomepage\fP"
.br
.ti -1c
.RI "std::string \fBbuypage\fP"
.br
.ti -1c
.RI "std::string \fBtags\fP"
.br
.ti -1c
.RI "float \fBprice\fP"
.br
.ti -1c
.RI "bool \fBisDemo\fP"
.br
.ti -1c
.RI "bool \fBhasPaypal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file datalist\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
