.TH "DataList" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataList \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBEntry\fP"
.br
.ti -1c
.RI "struct \fBTigInfo\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (const std::string &urlname, const std::string &idname, const std::string &name, const std::string &tigurl, int64_t add_time, bool isNew, const \fBTigInfo\fP &tigInfo, float rating, int rateCount, int dlCount)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBEntry\fP > \fBarr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file datalist\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
