.TH "DataList::Entry" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataList::Entry \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBadd_time\fP"
.br
.ti -1c
.RI "bool \fBisNew\fP"
.br
.ti -1c
.RI "float \fBrating\fP"
.br
.ti -1c
.RI "int \fBrateCount\fP"
.br
.ti -1c
.RI "int \fBdlCount\fP"
.br
.ti -1c
.RI "std::string \fBurlname\fP"
.br
.ti -1c
.RI "std::string \fBidname\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::string \fBtigurl\fP"
.br
.ti -1c
.RI "\fBTigInfo\fP \fBtigInfo\fP"
.br
.ti -1c
.RI "void * \fBinfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file datalist\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
