.TH "DownloadJob" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DownloadJob \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBThreadJob\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDownloadJob\fP (const std::string &_url, const std::string &_file)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBurl\fP"
.br
.ti -1c
.RI "std::string \fBfile\fP"
.br
.ti -1c
.RI "int \fBcurrent\fP"
.br
.ti -1c
.RI "int \fBtotal\fP"
.br
.ti -1c
.RI "bool \fBcompleted\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file downloadjob\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
