.TH "GameSortOptions" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSortOptions \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSortOptions\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddSortOptions\fP (wxWindow *parent, wxBoxSizer *pane) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1122 of file tiggit\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
