.TH "JsonInstalled" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsonInstalled \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBwrite\fP (\fBDataList\fP &data)"
.br
.ti -1c
.RI "void \fBread\fP (\fBDataList\fP &data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file json_installed\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
