.TH "Json::ValueConstIterator" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::ValueConstIterator \- 
.PP
const iterator for object and array value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <value\&.h>\fP
.PP
Inherits \fBJson::ValueIteratorBase\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBsize_t\fP"
.br
.ti -1c
.RI "typedef int \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef const Value & \fBreference\fP"
.br
.ti -1c
.RI "typedef const Value * \fBpointer\fP"
.br
.ti -1c
.RI "typedef \fBValueConstIterator\fP \fBSelfType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSelfType\fP & \fBoperator=\fP (const \fBValueIteratorBase\fP &other)"
.br
.ti -1c
.RI "\fBSelfType\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBSelfType\fP \fBoperator--\fP (int)"
.br
.ti -1c
.RI "\fBSelfType\fP & \fBoperator--\fP ()"
.br
.ti -1c
.RI "\fBSelfType\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "reference \fBoperator*\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
const iterator for object and array value\&. 

.PP
.nf
 .fi
.PP
 
.PP
Definition at line 949 of file value\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
