.TH "ListTabNonEmpty" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListTabNonEmpty \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBListTab\fP\&.
.PP
Inherited by \fBDemoListTab\fP, and \fBNewGameListTab\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBListTabNonEmpty\fP (wxNotebook *parent, const wxString &name, int listType, \fBStatusNotify\fP *s, const \fBSortOptions\fP *sop=NULL)"
.br
.ti -1c
.RI "void \fBinsertMe\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1135 of file tiggit\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
