.TH "MyFrame" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyFrame \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStatusNotify\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyFrame\fP (const wxString &title, const std::string &ver)"
.br
.ti -1c
.RI "\fBTabBase\fP * \fBgetTab\fP (int i)"
.br
.ti -1c
.RI "\fBTabBase\fP * \fBgetCurrentTab\fP ()"
.br
.ti -1c
.RI "void \fBsetTabFocus\fP ()"
.br
.ti -1c
.RI "void \fBsetupTabs\fP ()"
.br
.ti -1c
.RI "void \fBonLeftRight\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBonDataChanged\fP ()"
.br
.ti -1c
.RI "void \fBswitchToInstalled\fP ()"
.br
.ti -1c
.RI "void \fBonRefresh\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBonAbout\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBonExit\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBtick\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1239 of file tiggit\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
