.TH "MyTimer" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyTimer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyTimer\fP (\fBMyFrame\fP *f)"
.br
.ti -1c
.RI "void \fBNotify\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMyFrame\fP * \fBframe\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1478 of file tiggit\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
