.TH "NewGameListTab" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewGameListTab \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBListTabNonEmpty\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewGameListTab\fP (wxNotebook *parent, \fBStatusNotify\fP *s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1158 of file tiggit\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
