.TH "NewsItem" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewsItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBNewsItem\fP &other) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "time_t \fBdateNum\fP"
.br
.ti -1c
.RI "wxString \fBdate\fP"
.br
.ti -1c
.RI "wxString \fBsubject\fP"
.br
.ti -1c
.RI "wxString \fBbody\fP"
.br
.ti -1c
.RI "bool \fBread\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file newstab\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
