.TH "NewsList" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewsList \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewsList\fP (wxWindow *parent, int ID)"
.br
.ti -1c
.RI "void \fBsetData\fP (\fBNewsHolder\fP &n)"
.br
.ti -1c
.RI "\fBNewsItem\fP * \fBgetItem\fP (int item) const "
.br
.ti -1c
.RI "wxListItemAttr * \fBOnGetItemAttr\fP (long item) const "
.br
.ti -1c
.RI "wxString \fBOnGetItemText\fP (long item, long column) const "
.br
.ti -1c
.RI "bool \fBmarkAsRead\fP (int item)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 132 of file newstab\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
