.TH "NewsTab" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewsTab \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTabBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewsTab\fP (wxNotebook *parent)"
.br
.ti -1c
.RI "void \fBreloadData\fP ()"
.br
.ti -1c
.RI "void \fBonWebsite\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBonGetNews\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBonReadAll\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBonListSelect\fP (wxListEvent &event)"
.br
.ti -1c
.RI "void \fBupdateTabName\fP ()"
.br
.ti -1c
.RI "void \fBonListDeselect\fP (wxListEvent &event)"
.br
.ti -1c
.RI "void \fBonUrlEvent\fP (wxTextUrlEvent &event)"
.br
.ti -1c
.RI "void \fBtakeFocus\fP ()"
.br
.ti -1c
.RI "void \fBdataChanged\fP ()"
.br
.ti -1c
.RI "void \fBinsertMe\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNewsList\fP * \fBlist\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBtextView\fP"
.br
.ti -1c
.RI "\fBNewsHolder\fP \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 220 of file newstab\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
