.TH "PreLoad" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PreLoad \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBprocess\fP (const wxString &line)"
.br
.ti -1c
.RI "void \fBload\fP (const wxString &file)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBhasLoaded\fP"
.br
.ti -1c
.RI "bool \fBisSf\fP"
.br
.ti -1c
.RI "bool \fBisHost\fP"
.br
.ti -1c
.RI "wxString \fBversion\fP"
.br
.ti -1c
.RI "wxString \fBdesc\fP"
.br
.ti -1c
.RI "wxString \fBhomepage\fP"
.br
.ti -1c
.RI "wxString \fBurl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file tigmaker\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
