.TH "ProgressHolder" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProgressHolder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCacheFetcher\fP, and \fBUpdater\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgressHolder\fP (wxApp *_app)"
.br
.ti -1c
.RI "bool \fBsetMsg\fP (const std::string &str, int value=0)"
.br
.ti -1c
.RI "bool \fBupdate\fP (int value)"
.br
.ti -1c
.RI "bool \fBpulse\fP ()"
.br
.ti -1c
.RI "void \fByield\fP ()"
.br
.ti -1c
.RI "bool \fBsetMsg\fP (const wxString &str, int value=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file progress_holder\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
