.TH "RateSort" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RateSort \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSortBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRateSort\fP (\fBDataList\fP &d)"
.br
.ti -1c
.RI "bool \fBisLess\fP (\fBDataList::Entry\fP &a, \fBDataList::Entry\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file gen_webdata\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
