.TH "ThreadJob" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThreadJob \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStatusJob\fP\&.
.PP
Inherited by \fBDownloadJob\fP, \fBScreenshotLoader\fP, and \fBZipJob\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBwxJobRunner\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBrunAndDelete\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file jobify\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
