.TH "TmpDir" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TmpDir \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTmpDir\fP (const boost::filesystem::path &_dir)"
.br
.ti -1c
.RI "std::string \fBget\fP (const std::string &file)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::filesystem::path \fBdir\fP"
.br
.ti -1c
.RI "bool \fBcreated\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file tmpdir\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Tiggit from the source code\&.
