.TH "todo" 3 "Tue May 8 2012" "Tiggit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.IP "\fBClass \fBDefaultValueArrayAllocator\fP \fP" 1c
make this thread-safe (lock when accessign batch allocator)  
.IP "\fBClass \fBDefaultValueMapAllocator\fP \fP" 1c
make this thread-safe (lock when accessign batch allocator) 
.PP

